### ISSUE TITLE
Two SVG that cause an error...

### ISSUE THREAD

**Issue by DerAndereMicha** [ekot1/DelphiSVG#19]
The two attached graphics cause errors or cause the app to freeze completely.
[svg_error_maps.zip](https://github.com/ekot1/DelphiSVG/files/6134638/svg_error_maps.zip)

**Comment by DerAndereMicha** [comment]
One problem is still there -  SVG attached (stroke-dasharray is the problem)

The problem seems to be in the following procedure:

procedure TSVGBasic.SetStrokeDashArray(const S: string);
...
begin
...
  SetLength(FStrokeDashArray, SL.Count);
  FStrokeDashArrayCount := SL.Count;    //The line results in a freeze; If you comment them out it works. But whether everything is then displayed as desired, I don't know...
...
end;

Regards
Michael


[Mediterranean_Sea_location_map.zip](https://github.com/ekot1/DelphiSVG/files/6140460/Mediterranean_Sea_location_map.zip)

**Comment by ekot1** [comment]
> 
> 
> One problem is still there - SVG attached (stroke-dasharray is the problem)
> 
> The problem seems to be in the following procedure:
> 
> procedure TSVGBasic.SetStrokeDashArray(const S: string);
> ...
> begin
> ...
> SetLength(FStrokeDashArray, SL.Count);
> FStrokeDashArrayCount := SL.Count; //The line results in a freeze; If you comment them out it works. But whether everything is then displayed as desired, I don't know...
> ...
> end;
> 
> Regards
> Michael
> 
> [Mediterranean_Sea_location_map.zip](https://github.com/ekot1/DelphiSVG/files/6140460/Mediterranean_Sea_location_map.zip)

Try now, it should be fixed

**Comment by DerAndereMicha** [comment]
Looks good :-)

Thanks!
