### ISSUE TITLE
Style didn't change color

### ISSUE THREAD

**Issue by Rusland3000** [ekot1/DelphiSVG#2]
Trying to change color of the text element (id=text5040) from #000000 to #0000FF.
Nothing happens, color still black.

Code:
`procedure TForm1.Button1Click(Sender: TObject);
begin
  if OpenDialog1.Execute then
  begin
    SVGImage1.LoadFromFile(OpenDialog1.FileName);
    SVGImage1.SVG.FindByID('text5040').Style.AddStyle('fill', '#0000FF');
  end;
end;`

SVG text element: (it could be path, rectangle etc)
`    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="659.09045"
       y="657.46405"
       id="text5040">Some text</text>`

**Comment by ekot1** [comment]
I've added fix for this issue. You'll need to add SVGImage1.Invalidate to refresh image
