### ISSUE TITLE
Blurry SVG :(

### ISSUE THREAD

**Issue by kazuser** [ekot1/DelphiSVG#20]
![square](https://user-images.githubusercontent.com/3335273/153041218-ce40dbd2-87f9-42c1-b348-466dcdd405c2.svg)

Hi! Thanks for your library!

Tell me please, do you know why my pretty simple SVG is so... blurry?
![image](https://user-images.githubusercontent.com/3335273/153041532-edb9358a-9b65-431e-87c1-d6dc391fcac7.png)

Zoom in Delphi:
![image](https://user-images.githubusercontent.com/3335273/153042445-a4af99d3-e693-4897-9de3-afc3bfb41c31.png)

Original in Figma:
![image](https://user-images.githubusercontent.com/3335273/153042090-3f0688cf-08e7-4f8e-ba05-a81ec5443241.png)

**Comment by kazuser** [comment]
It's strange but even empty square is blurry too :(

`<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="32" height="32" fill="#FF0000"/></svg>`

![image](https://user-images.githubusercontent.com/3335273/153043907-c691fc99-3c31-4cb0-82e2-f79d5b6a0eed.png)

**Comment by ekot1** [comment]
By default it is rendered with antialiasing, I don't think it is possible to make it configurable when loading image.
You can change it yourself in BitmapCodecSVG.pas file find 
    Status := GPGraphics.SetSmoothingMode(SmoothingModeAntiAlias);
and change it to
    Status := GPGraphics.SetSmoothingMode(SmoothingModeNone);

then reinstall FMXSVGImage.bpl and reload image, it should not be blurry
